Task/Task/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView  # new


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'signup', include('users.urls', namespace='users')),
    url(r'order/', include('order.urls', namespace='order')),
    url('', TemplateView.as_view(template_name='home.html'), name='home'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Task/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^place/order$', views.place_order, name='place_order'),
]

Task/users/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.signup, name='signup'),
]

Task/order/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from users.models import CustomUser


def get_order_image_path(instance, filename):
    name = 'order/%s' % (
        filename)
    return name


class Order(models.Model):
    user = models.ForeignKey(CustomUser, default=None, blank=True, null=True)
    img = models.ImageField(
        upload_to=get_order_image_path,
        null=True, default=None, blank=True)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)

    def __str__(self):
        return self.address

Task/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User


def get_user_image_path(instance, filename):
    """
    Function to return the image path for user images.

    Input Params:
        instance (obj): instance object
        filename (str): Original file name of the file
    Output Params:
        path (str): path name for the file
    """
    name = 'profilepic/%s/%s/%s' % (
        instance.type,
        instance.user.first_name, filename)
    return name


class CustomUser(models.Model):
    """
    Root User model.

    Atribs:
        user (obj): Django user model.
        type (int): field define the type of the user
        access_token (char): Hex value representing the token of the
            user.
        image (img): user image.
        address(char): address of the user.
        active_devices (int): no of active devices of user.
        blocked(bool): field which shows the active status of user.
        phone (char): phone number of the user
    """

    user = models.OneToOneField(User)
    address = models.CharField(
        default='', max_length=2000, blank=True)
    phone = models.CharField(
        default='', max_length=200, blank=True)
    image = models.ImageField(
        upload_to=get_user_image_path,
        null=True, default=None, blank=True)
    blocked = models.BooleanField(default=False)

    @property
    def name(self):
        """Get user name."""
        return self.user.username

    @property
    def image_url(self):
        """Get file url name."""
        try:
            return self.image.url
        except:
            None

    def __unicode__(self):
        """Object name in django admin."""
        return '%s : %s' % (self.name, self.id)

Task/order/forms.py
from django import forms
from order.models import Order


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ['user']

Task/order/views.py
from order.forms import OrderForm
from django.shortcuts import render
from users.models import CustomUser
from django.http import HttpResponseRedirect
from django.urls import reverse


def place_order(request):
    if request.method == "POST":
        form = OrderForm(request.POST, request.FILES)

        if form.is_valid():
            data = form.save(commit=False)
            custm_user = CustomUser.objects.filter(user=request.user).first()
            data.user = custm_user
            data.save()
            return HttpResponseRedirect(reverse
                                        ('home'))
    else:
        form = OrderForm()

    return render(request, "order/index.html", {'form': form})

Task/users/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from .models import CustomUser


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            custom_user = CustomUser.objects.create(user=user)
            custom_user.save()
            login(request, user)
            return HttpResponseRedirect(reverse
                                        ('home'))
    else:
        form = UserCreationForm()
    return render(request, 'users/sign_up.html', {'form': form})

Task/order/templates/order/index.html
    <!DOCTYPE html>  
    <html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Order</title>  
    </head>  
    <body>  
    <form action="{% url 'order:place_order' %}" method="POST" enctype="multipart/form-data" class="post-form">  
            {% csrf_token %}  
            {{ form.as_p }}  
            <button type="submit" class="save btn btn-default">Save</button>  
        </form>  
    </body>  
    </html>  

Task/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

Task/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!

<h2> <a href="{% url 'order:place_order' %}">Place order</a></h2>

  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
  <h2>or</h2>
  <a href="{% url 'users:signup' %}">Sign up</a>
{% endif %}
{% endblock %}

Task/users/templates/users/sign_up.html
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}        
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit">Sign up</button>
</form>